### ISSUE TITLE
ClassHall 0.0.6 - Beta Version Doesn't Work on Beta

### ISSUE THREAD

**Issue by Calesta** [destroyerdust/Class-Hall#11]
I installed the latest 'beta' version (https://wow.curseforge.com/addons/class-hall/files/7-class-hall_v0-0-6_beta/) and both the minimap icon and the broker show no data.

P.S.  The folder extracted from the download was called 'Class-Hall-beta' and it wouldn't show up in the Addons menu until I renamed it to 'ClassHall' like the original 0.0.5 version.

**Comment by destroyerdust** [comment]
Hello Calesta,

Thanks for the bug report. Added to Milestone V0.0.7 which I want to put out by tomorrow because its a big issue since there is no data.

-DestroyerDust (Ahealen)

**Comment by destroyerdust** [comment]
Got caught up with stuff but V0.0.7_Beta has the follower information resolved.
